# Generated by Django 2.2.3 on 2019-07-24 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 7, 24, 13, 39, 53, 628557)),
        ),
    ]
